---
- name: "Creates directory"
  file:
    path: /home/ubuntu/backend
    state: directory
    
- name: "Move backend files to remote server."
  become: true
  copy:
    src: /root/project/backend
    dest: /home/ubuntu

- name: "NPM install"
  command: npm install
  args:
    chdir: /home/ubuntu/backend
    
- name: "build package"
  become: true
  shell: |
    cd /home/ubuntu/backend
    npm run build
- name: "run server"
  become: true
  shell: |
    cd /home/ubuntu/backend
    pm2 start npm -- run "start:dev"
    pm2 ls
